### ISSUE TITLE
Spot Id & lat/lon

### ISSUE THREAD

**Issue by jcconnell** [HowardRiddiough/msw#1]
What process have you used previously to aggregate the latitude and longitude for each spot id? I am working through the North American list by hand, using [latlong.net](https://www.latlong.net/. After doing about 20, I realized I don't want to do it inconsistent to what you've already done.

**Comment by HowardRiddiough** [comment]
Hello @jcconnell. Ah so you are collecting lat and long information for each spot. I was manually getting the lat and lon using google maps for each spot. Unfortunately I cant think of a better way, so I dont see any inconsistencies in what you are doing.

**Comment by jcconnell** [comment]
Thanks for the quick answer. I created a PR to add the North American spot ids. I like this repo and I'm interested in helping with some of your To-Dos. I'm also interested in possibly integrating it with Home Assistant.
